name: Generate Snake

on:
  schedule:
    # Executa todos os dias à meia-noite (GMT)
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    name: Generate snake animation
    runs-on: ubuntu-latest

    steps:
      # Cria o SVG da animação
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: jaqueline-silva4
          outputs: dist/github-contribution-grid-snake.svg

      # Publica o arquivo na branch "output"
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
