name: Atualização automática das métricas do perfil

permissions:
  contents: write     # PERMISSÃO OBRIGATÓRIA PARA FAZER COMMIT NO BRANCH

on:
  schedule:
    - cron: "0 */12 * * *"   # Atualiza a cada 12 horas
  workflow_dispatch:          # Permite rodar manualmente

jobs:
  update:
    name: Gerar métricas do perfil
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v3

     
